from typing import Protocol, List, Optional
from ..domain.city import City

class CityRepository(Protocol):
    def get(self, city_id: str) -> Optional[City]: ...
    def add(self, city: City) -> None: ...
    def update(self, city: City) -> None: ...
    def delete(self, city_id: str) -> None: ...
    def list_all(self) -> List[City]: ...
