from typing import Protocol, List, Optional
from ..domain.equipment import Equipment, Item

class EquipmentRepository(Protocol):
    def add_item(self, item: Item) -> None: ...
    def get_item(self, item_id: str) -> Optional[Item]: ...
    def list_items(self) -> List[Item]: ...
    def get_equipment(self, character_id: str) -> Optional[Equipment]: ...
    def save_equipment(self, equipment: Equipment) -> None: ...
