from typing import Protocol, List, Optional
from ..domain.spells import Spell, SpellBook

class SpellRepository(Protocol):
    def get_spell(self, spell_id: str) -> Optional[Spell]: ...
    def add_spell(self, spell: Spell) -> None: ...
    def list_spells(self) -> List[Spell]: ...
    def get_spell_book(self, character_id: str) -> Optional[SpellBook]: ...
    def save_spell_book(self, spell_book: SpellBook) -> None: ...
