from typing import Protocol, List, Optional, Dict
from ..domain.progression import SkillProgress

class ProgressionRepository(Protocol):
    def get_skill_progress(self, character_id: str, skill_name: str) -> Optional[SkillProgress]: ...
    def save_skill_progress(self, character_id: str, skill_progress: SkillProgress) -> None: ...
    def get_all_skills(self, character_id: str) -> List[SkillProgress]: ...
